# Generated by Django 4.1.3 on 2022-11-17 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ocurred_at", models.DateTimeField()),
                ("number_of_times", models.PositiveIntegerField(null=True)),
                ("situation_emotion", models.CharField(max_length=560, null=True)),
                ("afterwards_feeling", models.CharField(max_length=560, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Journal",
                "ordering": ["-ocurred_at"],
            },
        ),
        migrations.CreateModel(
            name="Thought",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ocurred_at", models.DateTimeField()),
                ("thought", models.CharField(max_length=560, null=True)),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="web.journal"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-ocurred_at"],
            },
        ),
        migrations.CreateModel(
            name="SportType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=560, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ocurred_at", models.DateTimeField()),
                ("duration", models.PositiveIntegerField(null=True)),
                (
                    "sport",
                    models.ForeignKey(
                        max_length=560, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="web.sporttype"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Sport",
                "ordering": ["-ocurred_at"],
            },
        ),
        migrations.CreateModel(
            name="ProsCons",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(max_length=560, null=True)),
                ("type", models.CharField(choices=[("pros", "Pros"), ("cons", "Cons")], max_length=10, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Measurements",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ocurred_at", models.DateTimeField()),
                ("weight", models.PositiveIntegerField(null=True)),
                ("height", models.PositiveIntegerField(null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-ocurred_at"],
            },
        ),
        migrations.CreateModel(
            name="HealReasons",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=560, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForTheBetterLife",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(max_length=1000, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ocurred_at", models.DateTimeField(null=True)),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("BF", "Breakfast"),
                            ("BR", "Brunch"),
                            ("LU", "Lunch"),
                            ("SN", "Snack"),
                            ("DI", "Dinner"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("food", models.CharField(max_length=1000, null=True)),
                ("amount", models.PositiveIntegerField(null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Food",
                "ordering": ["-ocurred_at"],
            },
        ),
    ]
